#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: fluentd-logging
#  namespace: argocd
#  annotations:
#    argocd.argoproj.io/sync-wave: "3"
#spec:
#  project: default
#  source:
#    repoURL: https://fluent.github.io/helm-charts
#    chart: fluentd
#    targetRevision: 0.2.6
#    helm:
#      values: |
#        env:
#        - name:  FLUENT_ELASTICSEARCH_HOST
#          value: "elasticsearch-logging-master"
#        - name:  FLUENT_ELASTICSEARCH_PORT
#          value: "9200"
#        resources:
#           requests:
#             cpu: 10m
#             memory: 128Mi
#           limits:
#             memory: 256Mi
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: logging