apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-0
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  capacity:
    storage: 7Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: es-0
  volumeMode: Filesystem
  local:
    path: /var/opt/es-data-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - es